---
repository:
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: false
  archived: false
branches:
- name: master
  protection:
    required_pull_request_reviews: null
    required_status_checks:
      strict: true
      contexts: ['continuous-integration/travis-ci']
    enforce_admins: null
    restrictions: null
    required_signatures: true
- name: modulesync
  protection:
    required_pull_request_reviews: null
    required_status_checks:
      strict: true
      contexts: ['continuous-integration/travis-ci']
    enforce_admins: null
    restrictions: null
    required_signatures: true
    allow_force_pushes: true
    allow_deletions: true
